name: Mobile FitSync
description: "SyncFit – Seu parceiro nas atividades físicas ao ar livre"
full_description: >
  O SyncFit é um aplicativo pensado para quem ama se movimentar ao ar livre, seja caminhando, correndo ou pedalando. 
  Com ele, você acompanha de forma simples e prática seu desempenho, como distância percorrida, calorias gastas e até os batimentos cardíacos, se estiver usando um smartwatch.

  Além disso, o app te ajuda a cuidar da saúde com lembretes de hidratação e um histórico completo das suas atividades, para que você veja sua evolução com clareza. 
  A interface é fácil de usar e foi feita para todo tipo de pessoa, desde quem está começando até atletas mais experientes.

  Com o SyncFit, seus treinos ficam mais organizados, eficientes e conectados com você.

  Funcionalidades:
    - Visualize relatórios com insights sobre sua evolução, metas e desempenho físico.
    - Receba notificações personalizáveis para lembrar de beber água durante e após os treinos.
    - Tenha acesso ao seu histórico completo de atividades com gráficos, comparações e progresso ao longo do tempo.

android: https://telegra.ph/Replace-this-link-07-23
iOS: https://telegra.ph/Replace-this-link-07-23
web: https://telegra.ph/Replace-this-link-07-23

screenshots:
  - https://github.com/moonholly0/fitsync/raw/main/_images/screenshots/fit1.png
  - https://github.com/moonholly0/fitsync/raw/main/_images/screenshots/fit2.png
  - https://github.com/moonholly0/fitsync/raw/main/_images/screenshots/fit3.png
  - https://github.com/moonholly0/fitsync/raw/main/_images/screenshots/fit4.png
  - https://github.com/moonholly0/fitsync/raw/main/_images/screenshots/fit5.png


producthunt: https://telegra.ph/Replace-this-link-07-23

companies:
  - url: https://telegra.ph/Replace-this-link-07-23
    image: androidpolice.png
  - url: https://telegra.ph/Replace-this-link-07-23
    image: producthunt.png
